### ISSUE TITLE
Feature request: inverse operation, start with a GitHub URL which contains hash line number(s), and open the file in VSCode at the designated line / code selection

### ISSUE THREAD

**Issue by danielweck** [riteshksriv/github-links#1]
Hello, great extension, thank you!
Very useful for code peer reviews over Slack / instant messaging, to exchange URLs whilst working locally from VSCode.
However the inverse functionality would be very useful too.

For example I would like to be able to copy such URL: `https://github.com/riteshksriv/github-links/blob/940510c9a331bffda6f85dfc3ccb31e5ab970c40/src/extension.ts#L9-L10`

https://github.com/riteshksriv/github-links/blob/940510c9a331bffda6f85dfc3ccb31e5ab970c40/src/extension.ts#L9-L10

...and to show `src/extension.ts` in VSCode with the code selection line 9-10 (extracted from the URL `#L9-L10`).

Any thoughts?

**Comment by riteshksriv** [comment]
Done with 3.0
