### ISSUE TITLE
[FIX] Add license to extension for publication on open-vsx

### ISSUE THREAD

**Issue by johannrichard** [riteshksriv/github-links#3]
Ritesh, great extension, thanks for building it. 

It would be great if it could also be added to the VSCodium OS extensions over at [https://open-vsx.org/](https://open-vsx.org/). Since the extension lacks a LICENSE file it won't yet be accepted in the repository at [open-vsx/publish-extensions](https://github.com/open-vsx/publish-extensions) as they require an OSS license.

Would you mind adding an appropriate one?

**Comment by riteshksriv** [comment]
Done with 3.0
